"""
Layered Bank and Wallet Mobile Payment Simulation System Using Python and MySQL
Class 12 Computer Science Project
"""

import hashlib
import os
import random
import uuid
from datetime import datetime
import tkinter as tk
from tkinter import ttk, messagebox, simpledialog

import mysql.connector
from mysql.connector import Error
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

# ---------------------- GLOBAL DATABASE CONFIGURATION ----------------------
DB_CONFIG = {
    "host": os.getenv("DB_HOST", "127.0.0.1"),
    "port": int(os.getenv("DB_PORT", "3306")),
    "user": os.getenv("DB_USER", "root"),
    "password": os.getenv("DB_PASSWORD", "root"),
    "database": os.getenv("DB_NAME", "layered_payment_system"),
}

MAX_TXN_LIMIT = 99999.0
BANK_UID_PREFIX = "BANK"
INTERNAL_LAYER_UID = "SYSTEM_LAYER"


def get_connection():
    """Create and return a new MySQL connection."""
    return mysql.connector.connect(**DB_CONFIG)


def hash_password(raw_password: str) -> str:
    """Hash a password using SHA-256."""
    return hashlib.sha256(raw_password.encode("utf-8")).hexdigest()


def generate_wallet_uid() -> str:
    """Generate a unique wallet UID using uuid4."""
    return str(uuid.uuid4())


def generate_bank_uid() -> str:
    """Generate a bank UID with random 10-digit number."""
    return f"{BANK_UID_PREFIX}{random.randint(10**9, 10**10 - 1)}"


def generate_txn_id() -> str:
    """Generate a unique transaction ID."""
    return f"TXN-{uuid.uuid4().hex[:16].upper()}"


def create_pdf_receipt(txn: dict):
    """Generate PDF receipt for a successful transaction."""
    filename = f"receipt_{txn['txn_id']}.pdf"
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "Transaction Receipt")

    c.setFont("Helvetica", 12)
    lines = [
        f"Transaction ID: {txn['txn_id']}",
        f"Transaction Type: {txn['txn_type']}",
        f"Sender UID: {txn['sender_uid']}",
        f"Receiver UID: {txn['receiver_uid']}",
        f"Amount: INR {txn['amount']:.2f}",
        f"Date & Time: {txn['date_time']}",
        f"Status: {txn['status']}",
    ]

    y = height - 100
    for line in lines:
        c.drawString(50, y, line)
        y -= 24

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y - 20, "Generated by Layered Payment Simulation System")
    c.save()


def register_user(name: str, username: str, password: str):
    """Register a new user with wallet and bank account."""
    conn = None
    cursor = None
    try:
        wallet_uid = generate_wallet_uid()
        bank_uid = generate_bank_uid()
        pass_hash = hash_password(password)

        conn = get_connection()
        conn.start_transaction()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT user_id FROM users WHERE username = %s", (username,))
        if cursor.fetchone():
            raise ValueError("Username already exists.")

        # Ensure generated bank UID is unique
        while True:
            cursor.execute("SELECT bank_uid FROM users WHERE bank_uid = %s", (bank_uid,))
            if not cursor.fetchone():
                break
            bank_uid = generate_bank_uid()

        cursor.execute(
            """
            INSERT INTO users (name, username, password_hash, wallet_uid, bank_uid, created_at)
            VALUES (%s, %s, %s, %s, %s, NOW())
            """,
            (name, username, pass_hash, wallet_uid, bank_uid),
        )

        cursor.execute("INSERT INTO wallet (wallet_uid, balance) VALUES (%s, %s)", (wallet_uid, 0.0))
        cursor.execute("INSERT INTO bank_account (bank_uid, balance) VALUES (%s, %s)", (bank_uid, 50000.0))

        conn.commit()
        return {"wallet_uid": wallet_uid, "bank_uid": bank_uid}

    except Exception:
        if conn:
            conn.rollback()
        raise
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def authenticate_user(username: str, password: str):
    """Authenticate user by username and hashed password."""
    conn = None
    cursor = None
    try:
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM users WHERE username = %s", (username,))
        user = cursor.fetchone()
        if not user:
            return None
        if user["password_hash"] != hash_password(password):
            return None
        return user
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def verify_password(username: str, password: str) -> bool:
    """Verify password for sensitive dashboard actions."""
    user = authenticate_user(username, password)
    return user is not None


def get_user_balances(wallet_uid: str, bank_uid: str):
    """Fetch wallet and bank balances."""
    conn = None
    cursor = None
    try:
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT balance FROM wallet WHERE wallet_uid = %s", (wallet_uid,))
        wallet_row = cursor.fetchone()

        cursor.execute("SELECT balance FROM bank_account WHERE bank_uid = %s", (bank_uid,))
        bank_row = cursor.fetchone()

        wallet_balance = wallet_row["balance"] if wallet_row else 0.0
        bank_balance = bank_row["balance"] if bank_row else 0.0
        return wallet_balance, bank_balance
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def record_transaction(cursor, sender_uid: str, receiver_uid: str, amount: float, txn_type: str, status: str):
    """Insert a transaction row and return transaction details."""
    txn_id = generate_txn_id()
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cursor.execute(
        """
        INSERT INTO transactions (txn_id, sender_uid, receiver_uid, amount, txn_type, date_time, status)
        VALUES (%s, %s, %s, %s, %s, NOW(), %s)
        """,
        (txn_id, sender_uid, receiver_uid, amount, txn_type, status),
    )
    return {
        "txn_id": txn_id,
        "sender_uid": sender_uid,
        "receiver_uid": receiver_uid,
        "amount": amount,
        "txn_type": txn_type,
        "date_time": now,
        "status": status,
    }


def validate_amount(amount: float):
    if amount <= 0:
        raise ValueError("Amount must be positive.")
    if amount > MAX_TXN_LIMIT:
        raise ValueError(f"Maximum allowed per transaction is INR {MAX_TXN_LIMIT:.0f}.")


def transfer_bank_to_wallet(bank_uid: str, wallet_uid: str, amount: float):
    """Transaction Type: BANK_TO_WALLET"""
    validate_amount(amount)
    conn = None
    cursor = None
    try:
        conn = get_connection()
        conn.start_transaction()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT balance FROM bank_account WHERE bank_uid = %s FOR UPDATE", (bank_uid,))
        bank_row = cursor.fetchone()
        if not bank_row:
            raise ValueError("Bank account not found.")
        if bank_row["balance"] < amount:
            raise ValueError("Insufficient bank balance.")

        cursor.execute("SELECT balance FROM wallet WHERE wallet_uid = %s FOR UPDATE", (wallet_uid,))
        if not cursor.fetchone():
            raise ValueError("Wallet not found.")

        cursor.execute("UPDATE bank_account SET balance = balance - %s WHERE bank_uid = %s", (amount, bank_uid))
        cursor.execute("UPDATE wallet SET balance = balance + %s WHERE wallet_uid = %s", (amount, wallet_uid))

        txn = record_transaction(cursor, bank_uid, wallet_uid, amount, "BANK_TO_WALLET", "SUCCESS")
        conn.commit()
        create_pdf_receipt(txn)
        return txn

    except Exception:
        if conn:
            conn.rollback()
        raise
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def transfer_wallet_to_bank(wallet_uid: str, bank_uid: str, amount: float):
    """Transaction Type: WALLET_TO_BANK"""
    validate_amount(amount)
    conn = None
    cursor = None
    try:
        conn = get_connection()
        conn.start_transaction()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT balance FROM wallet WHERE wallet_uid = %s FOR UPDATE", (wallet_uid,))
        wallet_row = cursor.fetchone()
        if not wallet_row:
            raise ValueError("Wallet not found.")
        if wallet_row["balance"] < amount:
            raise ValueError("Insufficient wallet balance.")

        cursor.execute("SELECT balance FROM bank_account WHERE bank_uid = %s FOR UPDATE", (bank_uid,))
        if not cursor.fetchone():
            raise ValueError("Bank account not found.")

        cursor.execute("UPDATE wallet SET balance = balance - %s WHERE wallet_uid = %s", (amount, wallet_uid))
        cursor.execute("UPDATE bank_account SET balance = balance + %s WHERE bank_uid = %s", (amount, bank_uid))

        txn = record_transaction(cursor, wallet_uid, bank_uid, amount, "WALLET_TO_BANK", "SUCCESS")
        conn.commit()
        create_pdf_receipt(txn)
        return txn

    except Exception:
        if conn:
            conn.rollback()
        raise
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def transfer_wallet_to_wallet(sender_wallet_uid: str, receiver_wallet_uid: str, amount: float):
    """Transaction Type: WALLET_TO_WALLET"""
    validate_amount(amount)
    if sender_wallet_uid == receiver_wallet_uid:
        raise ValueError("Sender and receiver wallet cannot be same.")

    conn = None
    cursor = None
    try:
        conn = get_connection()
        conn.start_transaction()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT balance FROM wallet WHERE wallet_uid = %s FOR UPDATE", (sender_wallet_uid,))
        sender_row = cursor.fetchone()
        if not sender_row:
            raise ValueError("Sender wallet not found.")
        if sender_row["balance"] < amount:
            raise ValueError("Insufficient wallet balance.")

        cursor.execute("SELECT balance FROM wallet WHERE wallet_uid = %s FOR UPDATE", (receiver_wallet_uid,))
        receiver_row = cursor.fetchone()
        if not receiver_row:
            raise ValueError("Receiver wallet not found.")

        cursor.execute(
            "UPDATE wallet SET balance = balance - %s WHERE wallet_uid = %s",
            (amount, sender_wallet_uid),
        )
        cursor.execute(
            "UPDATE wallet SET balance = balance + %s WHERE wallet_uid = %s",
            (amount, receiver_wallet_uid),
        )

        txn = record_transaction(
            cursor,
            sender_wallet_uid,
            receiver_wallet_uid,
            amount,
            "WALLET_TO_WALLET",
            "SUCCESS",
        )
        conn.commit()
        create_pdf_receipt(txn)
        return txn

    except Exception:
        if conn:
            conn.rollback()
        raise
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def fetch_recent_transactions(wallet_uid: str):
    """Fetch last 30 minutes transactions for a wallet."""
    conn = None
    cursor = None
    try:
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute(
            """
            SELECT txn_id, sender_uid, receiver_uid, amount, txn_type, date_time, status
            FROM transactions
            WHERE (sender_uid = %s OR receiver_uid = %s)
              AND date_time >= NOW() - INTERVAL 30 MINUTE
            ORDER BY date_time DESC
            """,
            (wallet_uid, wallet_uid),
        )
        return cursor.fetchall()
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def fetch_full_transactions(wallet_uid: str, bank_uid: str):
    """Fetch all transactions for wallet and bank UIDs."""
    conn = None
    cursor = None
    try:
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute(
            """
            SELECT txn_id, sender_uid, receiver_uid, amount, txn_type, date_time, status
            FROM transactions
            WHERE sender_uid IN (%s, %s) OR receiver_uid IN (%s, %s)
            ORDER BY date_time DESC
            """,
            (wallet_uid, bank_uid, wallet_uid, bank_uid),
        )
        return cursor.fetchall()
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def fetch_incoming_after(wallet_uid: str, after_datetime: datetime):
    """Fetch incoming wallet-to-wallet transactions after a timestamp."""
    conn = None
    cursor = None
    try:
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute(
            """
            SELECT txn_id, sender_uid, receiver_uid, amount, txn_type, date_time, status
            FROM transactions
            WHERE receiver_uid = %s
              AND txn_type = 'WALLET_TO_WALLET'
              AND date_time > %s
            ORDER BY date_time ASC
            """,
            (wallet_uid, after_datetime),
        )
        return cursor.fetchall()
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


class PaymentApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Layered Bank and Wallet Mobile Payment Simulation")
        self.root.geometry("960x650")

        self.current_user = None
        self.last_poll_time = datetime.now()

        self.main_frame = tk.Frame(self.root)
        self.main_frame.pack(fill="both", expand=True)

        self.build_login_screen()

    def clear_main(self):
        for widget in self.main_frame.winfo_children():
            widget.destroy()

    def build_login_screen(self):
        self.clear_main()

        container = tk.Frame(self.main_frame, padx=20, pady=20)
        container.pack(expand=True)

        tk.Label(container, text="Layered Payment System", font=("Arial", 20, "bold")).pack(pady=10)
        tk.Label(container, text="Login", font=("Arial", 14, "bold")).pack(pady=8)

        tk.Label(container, text="Username").pack(anchor="w")
        self.login_username = tk.Entry(container, width=35)
        self.login_username.pack(pady=5)

        tk.Label(container, text="Password").pack(anchor="w")
        self.login_password = tk.Entry(container, width=35, show="*")
        self.login_password.pack(pady=5)

        tk.Button(container, text="Login", width=30, command=self.handle_login).pack(pady=10)
        tk.Button(container, text="Create New Account", width=30, command=self.build_register_screen).pack(pady=5)

        note = "Tip: Open this app twice to test two users and transfer wallet-to-wallet in demo mode."
        tk.Label(container, text=note, fg="blue").pack(pady=12)

    def build_register_screen(self):
        self.clear_main()

        container = tk.Frame(self.main_frame, padx=20, pady=20)
        container.pack(expand=True)

        tk.Label(container, text="Register New User", font=("Arial", 16, "bold")).pack(pady=10)

        tk.Label(container, text="Full Name").pack(anchor="w")
        self.reg_name = tk.Entry(container, width=40)
        self.reg_name.pack(pady=5)

        tk.Label(container, text="Username").pack(anchor="w")
        self.reg_username = tk.Entry(container, width=40)
        self.reg_username.pack(pady=5)

        tk.Label(container, text="Password").pack(anchor="w")
        self.reg_password = tk.Entry(container, width=40, show="*")
        self.reg_password.pack(pady=5)

        tk.Button(container, text="Register", width=30, command=self.handle_register).pack(pady=10)
        tk.Button(container, text="Back to Login", width=30, command=self.build_login_screen).pack(pady=5)

    def handle_register(self):
        name = self.reg_name.get().strip()
        username = self.reg_username.get().strip()
        password = self.reg_password.get().strip()

        if not name or not username or not password:
            messagebox.showerror("Input Error", "All fields are required.")
            return

        if len(password) < 4:
            messagebox.showerror("Input Error", "Password must be at least 4 characters.")
            return

        try:
            result = register_user(name, username, password)
            msg = (
                f"Registration successful.\nWallet UID: {result['wallet_uid']}\n"
                f"Bank UID: {result['bank_uid']}\nInitial bank balance: INR 50000"
            )
            messagebox.showinfo("Success", msg)
            self.build_login_screen()
        except Error as e:
            messagebox.showerror("Database Error", str(e))
        except Exception as e:
            messagebox.showerror("Registration Failed", str(e))

    def handle_login(self):
        username = self.login_username.get().strip()
        password = self.login_password.get().strip()

        if not username or not password:
            messagebox.showerror("Input Error", "Username and password are required.")
            return

        try:
            user = authenticate_user(username, password)
            if not user:
                messagebox.showerror("Login Failed", "Invalid username or password.")
                return

            self.current_user = user
            self.last_poll_time = datetime.now()
            self.build_dashboard()
            self.start_notification_polling()
        except Error as e:
            messagebox.showerror("Database Error", str(e))

    def build_dashboard(self):
        self.clear_main()

        top = tk.Frame(self.main_frame, padx=12, pady=12)
        top.pack(fill="x")

        tk.Label(top, text=f"Welcome, {self.current_user['name']} ({self.current_user['username']})", font=("Arial", 14, "bold")).pack(anchor="w")

        self.wallet_balance_label = tk.Label(top, text="Wallet Balance: INR 0.00", font=("Arial", 12))
        self.wallet_balance_label.pack(anchor="w", pady=4)

        self.refresh_balances()

        button_frame = tk.Frame(self.main_frame, padx=10, pady=10)
        button_frame.pack(fill="x")

        tk.Button(button_frame, text="Transfer Bank → Wallet", width=30, command=self.ui_bank_to_wallet).grid(row=0, column=0, padx=6, pady=6)
        tk.Button(button_frame, text="Transfer Wallet → Bank", width=30, command=self.ui_wallet_to_bank).grid(row=0, column=1, padx=6, pady=6)
        tk.Button(button_frame, text="Send Money (Wallet → Wallet)", width=30, command=self.ui_wallet_to_wallet).grid(row=0, column=2, padx=6, pady=6)

        tk.Button(button_frame, text="View Full Transaction History (Password)", width=30, command=self.ui_view_full_history).grid(row=1, column=0, padx=6, pady=6)
        tk.Button(button_frame, text="View Bank Balance (Password)", width=30, command=self.ui_view_bank_balance).grid(row=1, column=1, padx=6, pady=6)
        tk.Button(button_frame, text="Refresh Dashboard", width=30, command=self.refresh_dashboard).grid(row=1, column=2, padx=6, pady=6)

        tk.Button(self.main_frame, text="Logout", width=20, command=self.logout).pack(pady=6)

        table_frame = tk.Frame(self.main_frame, padx=10, pady=10)
        table_frame.pack(fill="both", expand=True)

        tk.Label(table_frame, text="Transactions in Last 30 Minutes", font=("Arial", 12, "bold")).pack(anchor="w")

        columns = ("txn_id", "sender_uid", "receiver_uid", "amount", "txn_type", "date_time", "status")
        self.recent_tree = ttk.Treeview(table_frame, columns=columns, show="headings", height=12)
        for col in columns:
            self.recent_tree.heading(col, text=col)
            self.recent_tree.column(col, width=120, anchor="center")

        scroll_y = ttk.Scrollbar(table_frame, orient="vertical", command=self.recent_tree.yview)
        self.recent_tree.configure(yscroll=scroll_y.set)

        self.recent_tree.pack(side="left", fill="both", expand=True)
        scroll_y.pack(side="right", fill="y")

        self.refresh_recent_transactions()

    def refresh_balances(self):
        wallet_balance, _ = get_user_balances(self.current_user["wallet_uid"], self.current_user["bank_uid"])
        self.wallet_balance_label.config(text=f"Wallet Balance: INR {wallet_balance:.2f}")

    def refresh_recent_transactions(self):
        for item in self.recent_tree.get_children():
            self.recent_tree.delete(item)

        rows = fetch_recent_transactions(self.current_user["wallet_uid"])
        for row in rows:
            self.recent_tree.insert(
                "",
                "end",
                values=(
                    row["txn_id"],
                    row["sender_uid"],
                    row["receiver_uid"],
                    f"{row['amount']:.2f}",
                    row["txn_type"],
                    row["date_time"],
                    row["status"],
                ),
            )

    def refresh_dashboard(self):
        try:
            self.refresh_balances()
            self.refresh_recent_transactions()
        except Error as e:
            messagebox.showerror("Refresh Error", str(e))

    def ask_amount(self):
        amount = simpledialog.askfloat("Amount", f"Enter amount (Max INR {MAX_TXN_LIMIT:.0f})", minvalue=0.01)
        if amount is None:
            return None
        return float(amount)

    def ui_bank_to_wallet(self):
        amount = self.ask_amount()
        if amount is None:
            return
        try:
            txn = transfer_bank_to_wallet(self.current_user["bank_uid"], self.current_user["wallet_uid"], amount)
            messagebox.showinfo("Success", f"Transfer successful. Transaction ID: {txn['txn_id']}")
            self.refresh_dashboard()
        except Exception as e:
            messagebox.showerror("Transaction Failed", str(e))

    def ui_wallet_to_bank(self):
        amount = self.ask_amount()
        if amount is None:
            return
        try:
            txn = transfer_wallet_to_bank(self.current_user["wallet_uid"], self.current_user["bank_uid"], amount)
            messagebox.showinfo("Success", f"Transfer successful. Transaction ID: {txn['txn_id']}")
            self.refresh_dashboard()
        except Exception as e:
            messagebox.showerror("Transaction Failed", str(e))

    def ui_wallet_to_wallet(self):
        receiver_wallet_uid = simpledialog.askstring("Receiver Wallet UID", "Enter receiver wallet UID:")
        if not receiver_wallet_uid:
            return
        amount = self.ask_amount()
        if amount is None:
            return

        try:
            txn = transfer_wallet_to_wallet(self.current_user["wallet_uid"], receiver_wallet_uid.strip(), amount)
            messagebox.showinfo("Success", f"Money sent successfully. Transaction ID: {txn['txn_id']}")
            self.refresh_dashboard()
        except Exception as e:
            messagebox.showerror("Transaction Failed", str(e))

    def ui_view_full_history(self):
        password = simpledialog.askstring("Password Verification", "Enter your password:", show="*")
        if not password:
            return
        if not verify_password(self.current_user["username"], password):
            messagebox.showerror("Access Denied", "Incorrect password.")
            return

        rows = fetch_full_transactions(self.current_user["wallet_uid"], self.current_user["bank_uid"])
        win = tk.Toplevel(self.root)
        win.title("Full Transaction History")
        win.geometry("1100x450")

        cols = ("txn_id", "sender_uid", "receiver_uid", "amount", "txn_type", "date_time", "status")
        tree = ttk.Treeview(win, columns=cols, show="headings")
        for col in cols:
            tree.heading(col, text=col)
            tree.column(col, width=150, anchor="center")

        for row in rows:
            tree.insert(
                "",
                "end",
                values=(
                    row["txn_id"],
                    row["sender_uid"],
                    row["receiver_uid"],
                    f"{row['amount']:.2f}",
                    row["txn_type"],
                    row["date_time"],
                    row["status"],
                ),
            )
        tree.pack(fill="both", expand=True)

    def ui_view_bank_balance(self):
        password = simpledialog.askstring("Password Verification", "Enter your password:", show="*")
        if not password:
            return
        if not verify_password(self.current_user["username"], password):
            messagebox.showerror("Access Denied", "Incorrect password.")
            return

        _, bank_balance = get_user_balances(self.current_user["wallet_uid"], self.current_user["bank_uid"])
        messagebox.showinfo("Bank Balance", f"Bank Balance: INR {bank_balance:.2f}")

    def start_notification_polling(self):
        if not self.current_user:
            return

        try:
            incoming = fetch_incoming_after(self.current_user["wallet_uid"], self.last_poll_time)
            for txn in incoming:
                message = (
                    f"You received INR {txn['amount']:.2f}\n"
                    f"From Wallet: {txn['sender_uid']}\n"
                    f"Transaction ID: {txn['txn_id']}"
                )
                messagebox.showinfo("New Incoming Payment", message)
                txn_time = txn["date_time"]
                if isinstance(txn_time, datetime) and txn_time > self.last_poll_time:
                    self.last_poll_time = txn_time

            self.last_poll_time = datetime.now()
            self.refresh_dashboard()
        except Exception:
            # Keep polling alive even if one cycle fails.
            pass

        self.root.after(5000, self.start_notification_polling)

    def logout(self):
        self.current_user = None
        self.build_login_screen()


def check_database_connection():
    """Validate initial DB connectivity before launching GUI."""
    conn = None
    try:
        conn = get_connection()
        return True
    except Error as e:
        messagebox.showerror("Database Connection Error", f"Unable to connect to MySQL:\n{e}")
        return False
    finally:
        if conn:
            conn.close()


def main():
    root = tk.Tk()
    app = PaymentApp(root)
    if check_database_connection():
        root.mainloop()
    else:
        root.destroy()


if __name__ == "__main__":
    main()
